### ISSUE TITLE
List (itemize) support for LaTeX without new line before the list

### ISSUE THREAD

**Issue by galou** [jupyter/jupyter#169]
Lists with no new line before them are rendered (falsely?) as lists but are not exported as itemize-environment in LaTeX.

Minimal example

``` yaml
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "No new line\n",
    "- item 1\n",
    "- item 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "With new line\n",
    "\n",
    "- item 1\n",
    "- item 2"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.3"
  },
  "toc": {
   "toc_cell": false,
   "toc_number_sections": true,
   "toc_threshold": 6,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

The first cell (with no new line before the list) and the second cell (with this new line) are rendered the same way in the notebook but only the second one is exported as itemize-environment. This causes confusion.
I use Jupyter 4.0.6.
